#!/bin/bash

set -eo pipefail

GORELEASER_VERSION=v0.138.0

cd "$(dirname "$0")/.." || exit

case "$1" in
"release")
            github-release-notes -org markphelps -repo flipt --since-latest-release | tee release.out

            docker run --rm --privileged \
              -v "$PWD":/flipt \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -w /flipt \
              -e GITHUB_TOKEN \
              -e DOCKER_USERNAME \
              -e DOCKER_PASSWORD \
              goreleaser/goreleaser:"$GORELEASER_VERSION"-cgo --rm-dist --release-notes release.out

            rm release.out
            ;;

"snapshot")
            docker run --rm --privileged \
              -v "$PWD":/flipt \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -w /flipt \
              goreleaser/goreleaser:"$GORELEASER_VERSION"-cgo --rm-dist --snapshot
            ;;
*)  echo "unknown command"
    ;;
esac
