#!/bin/bash

set -eo pipefail

OUTPUT_DIR=${OUTPUT_DIR:-".."}

cd "$(dirname "$0")/.." || exit

if ! command -v "protoc" &> /dev/null; then
    echo "protoc required but not installed!"
    exit 1
fi

case "$1" in
"go")
        GO_OUTPUT_DIR=$(realpath "${OUTPUT_DIR}/flipt-grpc-go")

        echo "--> generating Go client to $GO_OUTPUT_DIR ..."
        protoc -I rpc/ rpc/flipt.proto --go_out=plugins=grpc:"$GO_OUTPUT_DIR"
        ;;
"ruby")
        if ! command -v "grpc_tools_ruby_protoc" &> /dev/null; then
            echo "--> installing ruby dependencies..."
            gem install grpc-tools
        fi

        RUBY_OUTPUT_DIR=$(realpath "${OUTPUT_DIR}/flipt-grpc-ruby/lib") 

        echo "--> generating Ruby client to $RUBY_OUTPUT_DIR ..."

        grpc_tools_ruby_protoc -I rpc/ --ruby_out="$RUBY_OUTPUT_DIR" --grpc_out="$RUBY_OUTPUT_DIR" rpc/flipt.proto
        ;;
*)  echo "unknown command"
    ;;
esac